# These options accept old formated text with § symbols before formatting code.
# Reason for this is cus im lazy and don't want to write converter to newer "raw json" format,
# and it will make config file way too cluttered. And most of them don't event accept raw json
# as it is coded that way by mojank. Coping so hard rn.
# Leaving text field epmty skipps the line where it is possible.
#
# Codes:
# -Colors:
# 0 - Black;     1 - Dark blue;    2 - Dark green; 3 - Dark aqua;
# 4 - Dark red;  5 - Dark purple;  6 - Gold;       7 - Gray;
# 8 - Dark gray; 9 - Blue;         a - Green;      b - Aqua;
# c - Red;       d - Light purple; e - Yellow;     f - White;
# -Decoration:
# k - Magic(constantly changing gibberish);
# l - Bold;      m - Strikethrough;
# n - Underline; o - Italic;
# r - Reset decoration and color;
# -Example: §4§l§odark red bold italic text§r - §a§n§ogreen underlined italic text.

#                                          [[[SIDEBAR CONFIGURATIONS]]]

sidebar-label: "§3§lSculk Alarm"

sidebar-level-label: "§aCurrent alarm level:"
#level strings will be appended at the end of this message.
sidebar-level-prefix: "§a - "
sidebar-level-0: "§20"
sidebar-level-1: "§e1"
sidebar-level-2: "§62"
sidebar-level-3: "§43"
sidebar-level-4: "§34"

sidebar-seconds-label-line-1: "§aSeconds until alarm"
sidebar-seconds-label-line-2: "§alevel decreases:"
#seconds left will be appended at the end of this message. Will not change color dynamically. Cus... im lazy :P
sidebar-seconds-prefix: "§a - §6"

sidebar-comment-level-0-line-1: "§2§oWell done!"
sidebar-comment-level-0-line-2: ""
sidebar-comment-level-1-line-1: "§e§oWell... you are safe."
sidebar-comment-level-1-line-2: "§e§oFor now..."
sidebar-comment-level-2-line-1: "§6§oYou were supposed"
sidebar-comment-level-2-line-2: "§6§oto be silent..."
sidebar-comment-level-3-line-1: "§4§oI suggest you runnin'"
sidebar-comment-level-3-line-2: "§4§oouta' there, boi"
sidebar-comment-level-4-line-1: "§3§oI CAN HEAR YOU"
sidebar-comment-level-4-line-2: ""

sidebar-image: 1 # 1|0

#                                            [[[CHAT CONFIGURATIONS]]]

#level messages will be appended at %level%.
chat-level-label: "§aYou have sculk alarm level of %level%"

chat-level-0: "§20§r."
chat-level-1: "§e1§r."
chat-level-2: "§62§r."
chat-level-3: "§43§r."
chat-level-4: "§34§r."

#seconds left will be appended at %seconds%. Will not change color dynamically. Cus... im lazy :P
chat-seconds-label: "\n§aIt will decrease in §6%seconds% §aseconds"

chat-comment-level-0-label: "\n§2§oWell done!"
chat-comment-level-1-label: "\n§e§oWell... you are safe.\nFor now..."
chat-comment-level-2-label: "\n§6§oYou were supposed to be silent..."
chat-comment-level-3-label: "\n§4§oI suggest you runnin' outa' there, boi"
chat-comment-level-4-label: "\n§3§oI CAN HEAR YOU"
