name: SculkAlram
version: '${project.version}'
main: com.gibbdev.SculkAlram
api-version: 1.19
authors: [ GibbDev ]
description: Small Plugin that allows players to see thier current sculk warning level
website: https://github.com/GibberishDev/skulkalarm
commands:
  sa_appearance:
    description: Allows to toggle sculk alarm appearance
  sa_toggle:
    description: Allows to toggle if alram gui appears on interact with recovery compass